services:
  - type: web
    name: cashflow-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        fromDatabase:
          name: cashflow-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: cashflow-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cashflow-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: cashflow-db
          property: database
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: FRONTEND_URL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: RESEND_API_KEY
        sync: false
    databases:
      - name: cashflow-db
        databaseName: cashflow
        user: cashflow_user
        plan: free 