services:
  - type: web
    name: cashflow-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        value: postgres://cashflow_user:qpNW9j7p1Nof42zfEbzG2eM209swyt7d@dpg-cvlvohe3jp1c738rbo2g-a.oregon-postgres.render.com/cashflow_56jv
      - key: DB_HOST
        value: dpg-cvlvohe3jp1c738rbo2g-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        value: cashflow_user
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: cashflow_56jv
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: FRONTEND_URL
        value: https://cashflowfinance.vercel.app
      - key: EMAIL_FROM
        sync: false
      - key: RESEND_API_KEY
        sync: false
    databases:
      - name: cashflow-db
        databaseName: cashflow_56jv
        user: cashflow_user
        plan: free 